# Generated by Django 5.1.3 on 2024-12-03 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nike_name",
                    models.CharField(
                        blank=True, default="", max_length=23, verbose_name="Nike_Name"
                    ),
                ),
                (
                    "desc",
                    models.TextField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="Personal Profile",
                    ),
                ),
                (
                    "gexing",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Personalised Signature",
                    ),
                ),
                (
                    "birthday",
                    models.DateField(blank=True, null=True, verbose_name="Birthday"),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "male"), ("female", "female")],
                        default="male",
                        max_length=6,
                        verbose_name="Gender",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="Address"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        default="images/default.png",
                        upload_to="images/%Y/%m",
                        verbose_name="Avatar",
                    ),
                ),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
        ),
    ]
